apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: trading_db
    user: trading_user
    secureJsonData:
      password: 'trading_pass_change_in_production'
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1600
      timescaledb: true
    editable: true
    isDefault: true
